
server:
  # 端口号设置
  port: 8083

spring:
  # MySQL 设置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.97.218.237:3306/sc?useUnicode=true&useSSL=true&characterEncoding=utf8
    username: root
    password: Kkzzxx123.
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

      stat-view-servlet:
        allow: true
  # 时间格式设置
  jackson:
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


# Mybatis-plus 设置
mybatis-plus:
  # 配置Mybatis映射文件
  mapper-locations: classpath:mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.sc.entity

# JWT 配置

jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  # JWT 加密使用的密钥
  secret: bbs-secret
  # JWT 的超时期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer


# 动态图片服务器的配置信息
portrait_storage:
  ip:47.97.218.237
  port:8084
  path:/avatar/

# 动态图片服务器的配置信息
pic_storage:
  ip:47.97.218.237
  port:8084
  path:/picture/

# 视频服务器的配置信息
vid_storage:
  ip:47.97.218.237
  port:8084
  path:/video/

